# Generated by Django 3.0.5 on 2020-04-30 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstate',
            name='state',
            field=models.CharField(choices=[('NEW', 'NEW'), ('ACC', 'ACCEPTED'), ('COM', 'COMPLETED'), ('DEC', 'LOW'), ('CAN', 'CAN')], default='NEW', max_length=3),
        ),
    ]
